import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const origin=process.env.STUDIO_TEST_ORIGIN||'http://localhost:5173';
if(!/^http:\/\/(localhost|127\.0\.0\.1):\d+$/.test(origin))throw Error('Tests are local-only.');
let passed=0;const check=(description,fn)=>{fn();passed++;console.log('PASS '+description);};
async function req(path,{method='GET',data,auth=true,headers={}}={}){const response=await fetch(origin+'/api/studio/'+path,{method,headers:{...(auth?{Cookie:process.env.STUDIO_TEST_COOKIE||''}:{}),...(data instanceof FormData?{}:{'Content-Type':'application/json'}),...headers},body:data===undefined?undefined:data instanceof FormData?data:JSON.stringify(data)});let result;try{result=await response.json();}catch{result=null;}return {status:response.status,data:result};}
const ref=JSON.parse(readFileSync(new URL('../lib/reference-catalog.json',import.meta.url),'utf8'));
check('Catálogo 2026: 18 modelos de recipientes, 37 cores, 40 pares modelo/impressão, 512 variantes',()=>{assert.equal(ref.palettes.length,18);assert.equal(ref.names.length,37);assert.equal(ref.palettes.reduce((n,p)=>n+p.prints.length,0),40);assert.equal(ref.palettes.reduce((n,p)=>n+p.prints.length*p.indices.length,0),512);});
check('Catalog indices are valid and variants are unique',()=>{for(const p of ref.palettes){assert.equal(new Set(p.indices).size,p.indices.length);assert(p.indices.every(i=>i>=0&&i<ref.names.length));}});
let r=await req('designs',{auth:false});check('Anonymous user cannot list designs',()=>assert.equal(r.status,401));
r=await req('designs',{method:'POST',data:{name:'wrong origin'},headers:{Origin:'https://untrusted.invalid'}});check('Cross-origin mutation blocked',()=>assert.equal(r.status,403));
r=await req('designs',{method:'POST',data:{name:'TESTE LOCAL · validação de fluxo'}});check('Create draft persists',()=>assert.equal(r.status,201));let d=r.data;
r=await req('designs/'+d.id+'/publish',{method:'POST',data:{version:d.version}});check('Incomplete design cannot publish',()=>assert.equal(r.status,400));
const p={id:crypto.randomUUID(),print:'DIGITAL 360',model:'COPO ECO 450 ML',color:'BRANCO OPACO',art:null};
r=await req('designs/'+d.id,{method:'PUT',data:{...d,products:[{...p,model:'COPO DESCARTÁVEL 110 ML'}]}});check('Invalid model/print pairing blocked server-side',()=>assert.equal(r.status,400));
r=await req('designs/'+d.id,{method:'PUT',data:{...d,products:Array.from({length:6},()=>({...p,id:crypto.randomUUID()}))}});check('Maximum five products enforced',()=>assert.equal(r.status,400));
r=await req('designs/'+d.id,{method:'PUT',data:{...d,products:[p]}});check('Save product persists',()=>assert.equal(r.status,200));const stale=d.version;d=r.data;
r=await req('designs/'+d.id,{method:'PUT',data:{...d,version:stale,name:'stale'}});check('Concurrent stale save rejected',()=>assert.equal(r.status,409));
const bad=new FormData();bad.append('file',new File(['this is not an image'], 'fake.png',{type:'image/png'}));
r=await req('designs/'+d.id+'/assets',{method:'POST',data:bad});check('Fake image rejected',()=>assert.equal(r.status,415));
const good=new FormData();const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aZ1kAAAAASUVORK5CYII=','base64');good.append('file',new File([png],'validacao.png',{type:'image/png'}));
r=await req('designs/'+d.id+'/assets',{method:'POST',data:good});check('PNG upload persists',()=>assert.equal(r.status,201));const art=r.data;
r=await req('designs/'+d.id,{method:'PUT',data:{...d,products:[{...p,art}]}});check('Attach artwork persists',()=>assert.equal(r.status,200));d=r.data;
r=await req('designs/'+d.id);check('Reload returns saved artwork',()=>assert.equal(r.data.products[0].art.id,art.id));
r=await req('designs/'+d.id+'/publish',{method:'POST',data:{version:d.version}});check('Valid design publishes for 30 days',()=>{assert.equal(r.status,200);assert(Math.abs(r.data.expiresAt-Date.now()-30*86400000)<10000);});d=r.data;const firstToken=d.token;
r=await req('public/'+d.token,{auth:false});check('Valid shared token opens without editor login',()=>assert.equal(r.status,200));
let response=await fetch(origin+'/api/studio/assets/'+art.id);check('Unshared artwork needs authorization',()=>assert.equal(response.status,403));
response=await fetch(origin+'/api/studio/assets/'+art.id+'?token='+d.token);check('Shared artwork is available for active token',()=>{assert.equal(response.status,200);assert.equal(response.headers.get('content-type'),'image/png');});
r=await req('designs/'+d.id+'/publish',{method:'POST',data:{version:d.version}});d=r.data;check('Regenerating link rotates token',()=>assert.notEqual(d.token,firstToken));
r=await req('public/'+firstToken,{auth:false});check('Previous token invalid after renewal',()=>assert.equal(r.status,410));
r=await req('designs/'+d.id+'/expire',{method:'POST',data:{version:d.version}});check('Revoke persists',()=>assert.equal(r.status,200));d=r.data;
r=await req('public/'+d.token,{auth:false});check('Expired link cannot open',()=>assert.equal(r.status,410));
response=await fetch(origin+'/api/studio/assets/'+art.id+'?token='+d.token);check('Expired token cannot fetch artwork',()=>assert.equal(response.status,403));
r=await req('public/unknown-token',{auth:false});check('Unknown token fails closed',()=>assert.equal(r.status,410));
r=await req('designs/'+d.id+'/publish',{method:'POST',data:{version:d.version}});d=r.data;
r=await req('designs/'+d.id+'/revoke',{method:'POST',data:{version:d.version}});check('Revocation recorded separately from expiration',()=>{assert.equal(r.status,200);assert(r.data.revokedAt);assert(r.data.expiresAt>Date.now());});d=r.data;
r=await req('public/'+d.token,{auth:false});check('Revoked link cannot open',()=>assert.equal(r.status,410));
r=await req('designs/'+d.id+'/publish',{method:'POST',data:{version:d.version}});check('Renewing revoked design clears revocation',()=>{assert.equal(r.status,200);assert.equal(r.data.revokedAt,null);});d=r.data;
await req('designs/'+d.id+'/expire',{method:'POST',data:{version:d.version}});
console.log(JSON.stringify({passed,localOnly:true,testDesignId:d.id}));

