"use client";
import {useState,type FormEvent} from "react";
import {Eye,EyeOff,LockKeyhole,Loader2} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
export default function LoginForm({mode="login"}:{mode?:"login"|"activate"|"password"}){
 const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[currentPassword,setCurrentPassword]=useState(""),[confirmation,setConfirmation]=useState(""),[visible,setVisible]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function submit(e:FormEvent){e.preventDefault();setError("");if(mode!=="login"&&confirmation!==password){setError("As senhas não coincidem.");return;}setBusy(true);try{const r=await fetch(`/api/auth/${mode}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password,currentPassword})});const b=await r.json() as {error?:string};if(!r.ok)throw Error(b.error||"Não foi possível entrar.");location.assign("/");}catch(e){setError((e as Error).message);setBusy(false);}}
 return <main className="ecojoi-login"><div className="login-brand"><img className="login-identity" src="/brand/ecojoi-identidade.jpeg" width={590} height={340} alt="ECOJOI — Seja eco com ECOJOI"/><strong className="login-studio-title">Studio 3D</strong></div><section className="login-card"><div className="login-symbol"><LockKeyhole size={24}/></div><h1>{mode==="login"?"Bem-vindo ao Studio":mode==="activate"?"Ative seu acesso ECOJOI":"Alterar senha"}</h1><p>{mode==="login"?"Entre para criar e gerenciar suas amostras virtuais.":"Escolha uma senha com pelo menos 12 caracteres."}</p><form onSubmit={submit}>{mode==="login"&&<label className="field">E-mail<Input type="email" autoComplete="username" required maxLength={254} placeholder="voce@ecojoi.com.br" value={email} onChange={e=>setEmail(e.target.value)}/></label>}{mode==="password"&&<label className="field">Senha atual<Input type="password" autoComplete="current-password" required maxLength={128} value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)}/></label>}<label className="field">{mode==="login"?"Senha":"Nova senha"}<div className="login-password"><Input type={visible?"text":"password"} autoComplete={mode==="login"?"current-password":"new-password"} required minLength={12} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)}/><Button type="button" variant="ghost" size="icon" aria-label={visible?"Ocultar senha":"Mostrar senha"} onClick={()=>setVisible(!visible)}>{visible?<EyeOff size={18}/>:<Eye size={18}/>}</Button></div></label>{mode!=="login"&&<label className="field">Confirmar nova senha<Input type="password" autoComplete="new-password" required minLength={12} maxLength={128} value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label>}{error&&<p className="login-error" role="alert">{error}</p>}<Button type="submit" className="primary login-submit" disabled={busy}>{busy?<><Loader2 size={18} className="spin"/>Aguarde…</>:mode==="login"?"Entrar":mode==="activate"?"Ativar acesso":"Salvar nova senha"}</Button></form>{mode==="login"?<p className="login-help">Precisa de acesso ou esqueceu sua senha?<br/>Procure o responsável pelo Studio na ECOJOI.</p>:mode==="password"?<a href="/">Voltar aos designs</a>:null}</section><footer>ECOJOI · Amostras virtuais 3D</footer></main>;
}
